version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    # image: wordpress:4.9.6-php7.0-apache
    image: sesn/wordpress:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ".:/var/www/html/wp-content/themes/presspack"
      - "./wp-content/plugins:/var/www/html/wp-content/plugins"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    links:
      - db
    ports:
      - "9009:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 22222:80

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/bitnami
